name: Deploy

on:
  workflow_run:
    workflows: ["Build & Push"]
    types: [ completed ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: infra/terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: infra/terraform
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT }}
          TF_VAR_image: ${{ steps.build.outputs.IMAGE }}
        run: terraform apply -auto-approve

      - name: Mostrar URL
        run: |
          terraform output -raw url
