name: Build & Push

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build Docker image
        run: |
          IMAGE="us.gcr.io/${{ secrets.GCP_PROJECT }}/strapi-cms:${{ github.sha }}"
          docker build -t $IMAGE .
      - name: Push to Artifact Registry
        run: |
          IMAGE="us.gcr.io/${{ secrets.GCP_PROJECT }}/strapi-cms:${{ github.sha }}"
          docker push $IMAGE

      - name: Set image output
        run: echo "IMAGE=$IMAGE" >> $GITHUB_OUTPUT
