name: Build & Push

on:
  push:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Build Docker image
        run: |
          IMAGE="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/strapi-cms/strapi-cms:${{ github.sha }}"
          docker build -t $IMAGE .
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
          
      - name: Push to Google Artifact Registry
        run: |
          IMAGE="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/strapi-cms/strapi-cms:${{ github.sha }}"
          docker push $IMAGE

      - name: Set image output
        run: echo "IMAGE=$IMAGE" >> $GITHUB_OUTPUT
