name: Deploy

on:
  workflow_run:
    workflows: ["Build & Push"]
    types: [ completed ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: infra/terraform
        run: terraform init

      - name: Terraform Import Service Account
        working-directory: infra/terraform
        run: |
          terraform init -input=false
          terraform import google_service_account.sa projects/${{ secrets.GCP_PROJECT }}/serviceAccounts/strapi-sa@${{ secrets.GCP_PROJECT }}.iam.gserviceaccount.com

      - name: Terraform Apply
        working-directory: infra/terraform
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT }}
          TF_VAR_image: ${{ steps.build.outputs.IMAGE }}
        run: terraform apply -auto-approve

      - name: Mostrar URL
        run: |
          terraform output -raw url
